# Generated by Django 4.1.7 on 2023-04-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
