# Generated by Django 4.1.7 on 2023-04-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
