# Generated by Django 4.1.7 on 2023-04-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_savedpost_userprofile_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_posts',
        ),
    ]
