# Generated by Django 4.1.7 on 2023-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Artist', 'Artist'), ('Entrepreneur', 'Entrepreneur'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Influencer', 'Influencer'), ('Designer', 'Designer'), ('Photographer', 'Photographer'), ('Writer', 'Writer'), ('Musician', 'Musician'), ('Chef', 'Chef'), ('Athlete', 'Athlete'), ('Teacher', 'Teacher'), ('Scientist', 'Scientist'), ('Lawyer', 'Lawyer'), ('Student', 'Student'), ('Investor', 'Investor'), ('Freelancer', 'Freelancer'), ('Journalist', 'Journalist'), ('Consultant', 'Consultant'), ('Traveler', 'Traveler')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Prefer Not to Say', max_length=10),
        ),
    ]
