# Generated by Django 4.1.7 on 2023-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_account_type_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('PreferNotSay', 'Prefer Not to Say')], default='Prefer Not to Say', max_length=20),
        ),
    ]
