# Generated by Django 4.1.7 on 2023-04-28 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='close_friends',
            field=models.ManyToManyField(blank=True, related_name='close_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
