# Generated by Django 4.1.7 on 2023-05-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_close_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Prefer Not To Say', 'Prefer Not To Say'), ('Male', 'Male'), ('Female', 'Female')], default='Prefer Not To Say', max_length=20),
        ),
    ]
